// Mocks generated by Mockito 5.4.6 from annotations
// in car_care_app/test/features/logs/presentation/bloc/quick_log_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:car_care_app/core/services/location_service.dart' as _i8;
import 'package:car_care_app/core/services/ocr_service.dart' as _i10;
import 'package:car_care_app/core/services/receipt_parser_service.dart' as _i3;
import 'package:car_care_app/features/logs/data/models/fuel_log_model.dart'
    as _i6;
import 'package:car_care_app/features/logs/data/models/maintenance_log_model.dart'
    as _i7;
import 'package:car_care_app/features/logs/domain/repositories/log_repository.dart'
    as _i4;
import 'package:geolocator/geolocator.dart' as _i9;
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecognizedText_0 extends _i1.SmartFake
    implements _i2.RecognizedText {
  _FakeRecognizedText_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParsedFuelReceipt_1 extends _i1.SmartFake
    implements _i3.ParsedFuelReceipt {
  _FakeParsedFuelReceipt_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogRepository extends _i1.Mock implements _i4.LogRepository {
  MockLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addFuelLog(_i6.FuelLogModel? log) =>
      (super.noSuchMethod(
            Invocation.method(#addFuelLog, [log]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.FuelLogModel>> getRecentFuelLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFuelLogs, []),
            returnValue: _i5.Future<List<_i6.FuelLogModel>>.value(
              <_i6.FuelLogModel>[],
            ),
          )
          as _i5.Future<List<_i6.FuelLogModel>>);

  @override
  _i5.Future<void> addMaintenanceLog(_i7.MaintenanceLogModel? log) =>
      (super.noSuchMethod(
            Invocation.method(#addMaintenanceLog, [log]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.MaintenanceLogModel>> getMaintenanceLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenanceLogs, []),
            returnValue: _i5.Future<List<_i7.MaintenanceLogModel>>.value(
              <_i7.MaintenanceLogModel>[],
            ),
          )
          as _i5.Future<List<_i7.MaintenanceLogModel>>);

  @override
  _i5.Stream<List<_i6.FuelLogModel>> getFuelLogsStream(String? vehicleId) =>
      (super.noSuchMethod(
            Invocation.method(#getFuelLogsStream, [vehicleId]),
            returnValue: _i5.Stream<List<_i6.FuelLogModel>>.empty(),
          )
          as _i5.Stream<List<_i6.FuelLogModel>>);

  @override
  _i5.Stream<List<_i7.MaintenanceLogModel>> getMaintenanceLogsStream(
    String? vehicleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenanceLogsStream, [vehicleId]),
            returnValue: _i5.Stream<List<_i7.MaintenanceLogModel>>.empty(),
          )
          as _i5.Stream<List<_i7.MaintenanceLogModel>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i9.Position?> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i5.Future<_i9.Position?>.value(),
          )
          as _i5.Future<_i9.Position?>);
}

/// A class which mocks [OCRService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOCRService extends _i1.Mock implements _i10.OCRService {
  MockOCRService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RecognizedText> processImage(_i2.InputImage? inputImage) =>
      (super.noSuchMethod(
            Invocation.method(#processImage, [inputImage]),
            returnValue: _i5.Future<_i2.RecognizedText>.value(
              _FakeRecognizedText_0(
                this,
                Invocation.method(#processImage, [inputImage]),
              ),
            ),
          )
          as _i5.Future<_i2.RecognizedText>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ReceiptParserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReceiptParserService extends _i1.Mock
    implements _i3.ReceiptParserService {
  MockReceiptParserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ReceiptType detectReceiptType(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#detectReceiptType, [text]),
            returnValue: _i3.ReceiptType.fuel,
          )
          as _i3.ReceiptType);

  @override
  _i3.ParsedFuelReceipt parseFuelReceipt(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#parseFuelReceipt, [text]),
            returnValue: _FakeParsedFuelReceipt_1(
              this,
              Invocation.method(#parseFuelReceipt, [text]),
            ),
          )
          as _i3.ParsedFuelReceipt);

  @override
  List<_i3.POSItem> parsePOSReceipt(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#parsePOSReceipt, [text]),
            returnValue: <_i3.POSItem>[],
          )
          as List<_i3.POSItem>);

  @override
  List<_i3.ServiceItem> parseMechanicBill(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#parseMechanicBill, [text]),
            returnValue: <_i3.ServiceItem>[],
          )
          as List<_i3.ServiceItem>);

  @override
  String? extractBusinessName(String? text) =>
      (super.noSuchMethod(Invocation.method(#extractBusinessName, [text]))
          as String?);
}
