// Mocks generated by Mockito 5.4.6 from annotations
// in carlog/test/app_startup_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i15;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:cloud_firestore_platform_interface/cloud_firestore_platform_interface.dart'
    as _i7;
import 'package:firebase_analytics/firebase_analytics.dart' as _i12;
import 'package:firebase_analytics_platform_interface/firebase_analytics_platform_interface.dart'
    as _i13;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i3;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_performance/firebase_performance.dart' as _i6;
import 'package:firebase_performance_platform_interface/firebase_performance_platform_interface.dart'
    as _i14;
import 'package:google_sign_in/google_sign_in.dart' as _i5;
import 'package:google_sign_in/src/event_types.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_1 extends _i1.SmartFake
    implements _i3.ActionCodeInfo {
  _FakeActionCodeInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_2 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_3 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordValidationStatus_4 extends _i1.SmartFake
    implements _i3.PasswordValidationStatus {
  _FakePasswordValidationStatus_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInAuthorizationClient_5 extends _i1.SmartFake
    implements _i5.GoogleSignInAuthorizationClient {
  _FakeGoogleSignInAuthorizationClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGoogleSignInAccount_6 extends _i1.SmartFake
    implements _i5.GoogleSignInAccount {
  _FakeGoogleSignInAccount_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrace_7 extends _i1.SmartFake implements _i6.Trace {
  _FakeTrace_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpMetric_8 extends _i1.SmartFake implements _i6.HttpMetric {
  _FakeHttpMetric_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_9 extends _i1.SmartFake implements _i7.Settings {
  _FakeSettings_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_10<T extends Object?> extends _i1.SmartFake
    implements _i8.CollectionReference<T> {
  _FakeCollectionReference_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_11 extends _i1.SmartFake implements _i8.WriteBatch {
  _FakeWriteBatch_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_12 extends _i1.SmartFake
    implements _i8.LoadBundleTask {
  _FakeLoadBundleTask_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_13<T1 extends Object?> extends _i1.SmartFake
    implements _i8.QuerySnapshot<T1> {
  _FakeQuerySnapshot_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_14<T extends Object?> extends _i1.SmartFake
    implements _i8.Query<T> {
  _FakeQuery_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_15<T extends Object?> extends _i1.SmartFake
    implements _i8.DocumentReference<T> {
  _FakeDocumentReference_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_16<T1> extends _i1.SmartFake implements _i9.Future<T1> {
  _FakeFuture_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineSource_17 extends _i1.SmartFake
    implements _i8.PipelineSource {
  _FakePipelineSource_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i4.FirebaseAuth {
  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_0(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i9.Future<_i3.ActionCodeInfo>.value(
              _FakeActionCodeInfo_1(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.ActionCodeInfo>.value(
              _FakeActionCodeInfo_1(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i9.Future<_i3.ActionCodeInfo>);

  @override
  _i9.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Stream<_i4.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i9.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i9.Stream<_i4.User?>.empty(),
          )
          as _i9.Stream<_i4.User?>);

  @override
  _i9.Stream<_i4.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i9.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i9.Stream<_i4.User?>.empty(),
          )
          as _i9.Stream<_i4.User?>);

  @override
  _i9.Stream<_i4.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i9.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i9.Stream<_i4.User?>.empty(),
          )
          as _i9.Stream<_i4.User?>);

  @override
  _i9.Future<void> sendPasswordResetEmail({
    required String? email,
    _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setPersistence(_i3.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.UserCredential> signInWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.UserCredential> signInWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<_i4.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i4.ConfirmationResult>.value(
              _FakeConfirmationResult_3(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.ConfirmationResult>.value(
              _FakeConfirmationResult_3(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i9.Future<_i4.ConfirmationResult>);

  @override
  _i9.Future<_i4.UserCredential> signInWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i4.UserCredential>);

  @override
  _i9.Future<void> signInWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i3.PhoneMultiFactorInfo? multiFactorInfo,
    required _i3.PhoneVerificationCompleted? verificationCompleted,
    required _i3.PhoneVerificationFailed? verificationFailed,
    required _i3.PhoneCodeSent? codeSent,
    required _i3.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i3.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.PasswordValidationStatus> validatePassword(
    _i4.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePassword, [auth, password]),
            returnValue: _i9.Future<_i3.PasswordValidationStatus>.value(
              _FakePasswordValidationStatus_4(
                this,
                Invocation.method(#validatePassword, [auth, password]),
              ),
            ),
            returnValueForMissingStub:
                _i9.Future<_i3.PasswordValidationStatus>.value(
                  _FakePasswordValidationStatus_4(
                    this,
                    Invocation.method(#validatePassword, [auth, password]),
                  ),
                ),
          )
          as _i9.Future<_i3.PasswordValidationStatus>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i5.GoogleSignIn {
  @override
  _i9.Stream<_i11.GoogleSignInAuthenticationEvent> get authenticationEvents =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationEvents),
            returnValue:
                _i9.Stream<_i11.GoogleSignInAuthenticationEvent>.empty(),
            returnValueForMissingStub:
                _i9.Stream<_i11.GoogleSignInAuthenticationEvent>.empty(),
          )
          as _i9.Stream<_i11.GoogleSignInAuthenticationEvent>);

  @override
  _i5.GoogleSignInAuthorizationClient get authorizationClient =>
      (super.noSuchMethod(
            Invocation.getter(#authorizationClient),
            returnValue: _FakeGoogleSignInAuthorizationClient_5(
              this,
              Invocation.getter(#authorizationClient),
            ),
            returnValueForMissingStub: _FakeGoogleSignInAuthorizationClient_5(
              this,
              Invocation.getter(#authorizationClient),
            ),
          )
          as _i5.GoogleSignInAuthorizationClient);

  @override
  _i9.Future<void> initialize({
    String? clientId,
    String? serverClientId,
    String? nonce,
    String? hostedDomain,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #clientId: clientId,
              #serverClientId: serverClientId,
              #nonce: nonce,
              #hostedDomain: hostedDomain,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.GoogleSignInAccount?>? attemptLightweightAuthentication({
    bool? reportAllExceptions = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#attemptLightweightAuthentication, [], {
              #reportAllExceptions: reportAllExceptions,
            }),
            returnValueForMissingStub: null,
          )
          as _i9.Future<_i5.GoogleSignInAccount?>?);

  @override
  bool supportsAuthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#supportsAuthenticate, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool authorizationRequiresUserInteraction() =>
      (super.noSuchMethod(
            Invocation.method(#authorizationRequiresUserInteraction, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<_i5.GoogleSignInAccount> authenticate({
    List<String>? scopeHint = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {#scopeHint: scopeHint}),
            returnValue: _i9.Future<_i5.GoogleSignInAccount>.value(
              _FakeGoogleSignInAccount_6(
                this,
                Invocation.method(#authenticate, [], {#scopeHint: scopeHint}),
              ),
            ),
            returnValueForMissingStub:
                _i9.Future<_i5.GoogleSignInAccount>.value(
                  _FakeGoogleSignInAccount_6(
                    this,
                    Invocation.method(#authenticate, [], {
                      #scopeHint: scopeHint,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i5.GoogleSignInAccount>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [FirebaseAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAnalytics extends _i1.Mock implements _i12.FirebaseAnalytics {
  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_0(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i2.FirebaseApp);

  @override
  _i9.Future<String?> get appInstanceId =>
      (super.noSuchMethod(
            Invocation.getter(#appInstanceId),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i9.Future<bool>.value(false),
            returnValueForMissingStub: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<int?> getSessionId() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionId, []),
            returnValue: _i9.Future<int?>.value(),
            returnValueForMissingStub: _i9.Future<int?>.value(),
          )
          as _i9.Future<int?>);

  @override
  _i9.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
    List<_i13.AnalyticsEventItem>? items,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
              #items: items,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setConsent({
    bool? adStorageConsentGranted,
    bool? analyticsStorageConsentGranted,
    bool? adPersonalizationSignalsConsentGranted,
    bool? adUserDataConsentGranted,
    bool? functionalityStorageConsentGranted,
    bool? personalizationStorageConsentGranted,
    bool? securityStorageConsentGranted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setConsent, [], {
              #adStorageConsentGranted: adStorageConsentGranted,
              #analyticsStorageConsentGranted: analyticsStorageConsentGranted,
              #adPersonalizationSignalsConsentGranted:
                  adPersonalizationSignalsConsentGranted,
              #adUserDataConsentGranted: adUserDataConsentGranted,
              #functionalityStorageConsentGranted:
                  functionalityStorageConsentGranted,
              #personalizationStorageConsentGranted:
                  personalizationStorageConsentGranted,
              #securityStorageConsentGranted: securityStorageConsentGranted,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setDefaultEventParameters(
    Map<String, Object?>? defaultParameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultEventParameters, [defaultParameters]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setAnalyticsCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAnalyticsCollectionEnabled, [enabled]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setUserId({
    String? id,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [], {
              #id: id,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setUserProperty({
    required String? name,
    required String? value,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> resetAnalyticsData() =>
      (super.noSuchMethod(
            Invocation.method(#resetAnalyticsData, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logAddPaymentInfo({
    String? coupon,
    String? currency,
    String? paymentType,
    double? value,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddPaymentInfo, [], {
              #coupon: coupon,
              #currency: currency,
              #paymentType: paymentType,
              #value: value,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logAddShippingInfo({
    String? coupon,
    String? currency,
    double? value,
    String? shippingTier,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddShippingInfo, [], {
              #coupon: coupon,
              #currency: currency,
              #value: value,
              #shippingTier: shippingTier,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logAddToCart({
    List<_i13.AnalyticsEventItem>? items,
    double? value,
    String? currency,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddToCart, [], {
              #items: items,
              #value: value,
              #currency: currency,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logAddToWishlist({
    List<_i13.AnalyticsEventItem>? items,
    double? value,
    String? currency,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddToWishlist, [], {
              #items: items,
              #value: value,
              #currency: currency,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logAdImpression({
    String? adPlatform,
    String? adSource,
    String? adFormat,
    String? adUnitName,
    double? value,
    String? currency,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAdImpression, [], {
              #adPlatform: adPlatform,
              #adSource: adSource,
              #adFormat: adFormat,
              #adUnitName: adUnitName,
              #value: value,
              #currency: currency,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logAppOpen({
    _i13.AnalyticsCallOptions? callOptions,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAppOpen, [], {
              #callOptions: callOptions,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logBeginCheckout({
    double? value,
    String? currency,
    List<_i13.AnalyticsEventItem>? items,
    String? coupon,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBeginCheckout, [], {
              #value: value,
              #currency: currency,
              #items: items,
              #coupon: coupon,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logCampaignDetails({
    required String? source,
    required String? medium,
    required String? campaign,
    String? term,
    String? content,
    String? aclid,
    String? cp1,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCampaignDetails, [], {
              #source: source,
              #medium: medium,
              #campaign: campaign,
              #term: term,
              #content: content,
              #aclid: aclid,
              #cp1: cp1,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logEarnVirtualCurrency({
    required String? virtualCurrencyName,
    required num? value,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEarnVirtualCurrency, [], {
              #virtualCurrencyName: virtualCurrencyName,
              #value: value,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logGenerateLead({
    String? currency,
    double? value,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logGenerateLead, [], {
              #currency: currency,
              #value: value,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logJoinGroup({
    required String? groupId,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logJoinGroup, [], {
              #groupId: groupId,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logLevelUp({
    required int? level,
    String? character,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLevelUp, [], {
              #level: level,
              #character: character,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logLevelStart({
    required String? levelName,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLevelStart, [], {
              #levelName: levelName,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logLevelEnd({
    required String? levelName,
    int? success,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLevelEnd, [], {
              #levelName: levelName,
              #success: success,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logLogin({
    String? loginMethod,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLogin, [], {
              #loginMethod: loginMethod,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logPostScore({
    required int? score,
    int? level,
    String? character,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPostScore, [], {
              #score: score,
              #level: level,
              #character: character,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logPurchase({
    String? currency,
    String? coupon,
    double? value,
    List<_i13.AnalyticsEventItem>? items,
    double? tax,
    double? shipping,
    String? transactionId,
    String? affiliation,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPurchase, [], {
              #currency: currency,
              #coupon: coupon,
              #value: value,
              #items: items,
              #tax: tax,
              #shipping: shipping,
              #transactionId: transactionId,
              #affiliation: affiliation,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logRemoveFromCart({
    String? currency,
    double? value,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logRemoveFromCart, [], {
              #currency: currency,
              #value: value,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logScreenView({
    String? screenClass,
    String? screenName,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenClass: screenClass,
              #screenName: screenName,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logSelectItem({
    String? itemListId,
    String? itemListName,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectItem, [], {
              #itemListId: itemListId,
              #itemListName: itemListName,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logSelectPromotion({
    String? creativeName,
    String? creativeSlot,
    List<_i13.AnalyticsEventItem>? items,
    String? locationId,
    String? promotionId,
    String? promotionName,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectPromotion, [], {
              #creativeName: creativeName,
              #creativeSlot: creativeSlot,
              #items: items,
              #locationId: locationId,
              #promotionId: promotionId,
              #promotionName: promotionName,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logViewCart({
    String? currency,
    double? value,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewCart, [], {
              #currency: currency,
              #value: value,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logSearch({
    required String? searchTerm,
    int? numberOfNights,
    int? numberOfRooms,
    int? numberOfPassengers,
    String? origin,
    String? destination,
    String? startDate,
    String? endDate,
    String? travelClass,
    Map<String, Object>? parameters,
    _i13.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [], {
              #searchTerm: searchTerm,
              #numberOfNights: numberOfNights,
              #numberOfRooms: numberOfRooms,
              #numberOfPassengers: numberOfPassengers,
              #origin: origin,
              #destination: destination,
              #startDate: startDate,
              #endDate: endDate,
              #travelClass: travelClass,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logSelectContent({
    required String? contentType,
    required String? itemId,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectContent, [], {
              #contentType: contentType,
              #itemId: itemId,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logShare({
    required String? contentType,
    required String? itemId,
    required String? method,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logShare, [], {
              #contentType: contentType,
              #itemId: itemId,
              #method: method,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logSignUp({
    required String? signUpMethod,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSignUp, [], {
              #signUpMethod: signUpMethod,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logSpendVirtualCurrency({
    required String? itemName,
    required String? virtualCurrencyName,
    required num? value,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSpendVirtualCurrency, [], {
              #itemName: itemName,
              #virtualCurrencyName: virtualCurrencyName,
              #value: value,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logTutorialBegin({Map<String, Object>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logTutorialBegin, [], {#parameters: parameters}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logTutorialComplete({Map<String, Object>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logTutorialComplete, [], {
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logUnlockAchievement({
    required String? id,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logUnlockAchievement, [], {
              #id: id,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logViewItem({
    String? currency,
    double? value,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItem, [], {
              #currency: currency,
              #value: value,
              #items: items,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logViewItemList({
    List<_i13.AnalyticsEventItem>? items,
    String? itemListId,
    String? itemListName,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItemList, [], {
              #items: items,
              #itemListId: itemListId,
              #itemListName: itemListName,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logViewPromotion({
    String? creativeName,
    String? creativeSlot,
    List<_i13.AnalyticsEventItem>? items,
    String? locationId,
    String? promotionId,
    String? promotionName,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewPromotion, [], {
              #creativeName: creativeName,
              #creativeSlot: creativeSlot,
              #items: items,
              #locationId: locationId,
              #promotionId: promotionId,
              #promotionName: promotionName,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logViewSearchResults({
    required String? searchTerm,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewSearchResults, [], {
              #searchTerm: searchTerm,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logRefund({
    String? currency,
    String? coupon,
    double? value,
    double? tax,
    double? shipping,
    String? transactionId,
    String? affiliation,
    List<_i13.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logRefund, [], {
              #currency: currency,
              #coupon: coupon,
              #value: value,
              #tax: tax,
              #shipping: shipping,
              #transactionId: transactionId,
              #affiliation: affiliation,
              #items: items,
              #parameters: parameters,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logInAppPurchase({
    String? currency,
    bool? freeTrial,
    double? price,
    bool? priceIsDiscounted,
    String? productID,
    String? productName,
    int? quantity,
    bool? subscription,
    num? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logInAppPurchase, [], {
              #currency: currency,
              #freeTrial: freeTrial,
              #price: price,
              #priceIsDiscounted: priceIsDiscounted,
              #productID: productID,
              #productName: productName,
              #quantity: quantity,
              #subscription: subscription,
              #value: value,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> logTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#logTransaction, [transactionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSessionTimeoutDuration(Duration? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setSessionTimeoutDuration, [timeout]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initiateOnDeviceConversionMeasurementWithEmailAddress(
    String? emailAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithEmailAddress,
              [emailAddress],
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initiateOnDeviceConversionMeasurementWithPhoneNumber(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithPhoneNumber,
              [phoneNumber],
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initiateOnDeviceConversionMeasurementWithHashedEmailAddress(
    String? hashedEmailAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithHashedEmailAddress,
              [hashedEmailAddress],
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initiateOnDeviceConversionMeasurementWithHashedPhoneNumber(
    String? hashedPhoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithHashedPhoneNumber,
              [hashedPhoneNumber],
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [FirebasePerformance].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebasePerformance extends _i1.Mock
    implements _i6.FirebasePerformance {
  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_0(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<bool> isPerformanceCollectionEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isPerformanceCollectionEnabled, []),
            returnValue: _i9.Future<bool>.value(false),
            returnValueForMissingStub: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> setPerformanceCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setPerformanceCollectionEnabled, [enabled]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i6.Trace newTrace(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#newTrace, [name]),
            returnValue: _FakeTrace_7(
              this,
              Invocation.method(#newTrace, [name]),
            ),
            returnValueForMissingStub: _FakeTrace_7(
              this,
              Invocation.method(#newTrace, [name]),
            ),
          )
          as _i6.Trace);

  @override
  _i6.HttpMetric newHttpMetric(String? url, _i14.HttpMethod? httpMethod) =>
      (super.noSuchMethod(
            Invocation.method(#newHttpMetric, [url, httpMethod]),
            returnValue: _FakeHttpMetric_8(
              this,
              Invocation.method(#newHttpMetric, [url, httpMethod]),
            ),
            returnValueForMissingStub: _FakeHttpMetric_8(
              this,
              Invocation.method(#newHttpMetric, [url, httpMethod]),
            ),
          )
          as _i6.HttpMetric);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i8.FirebaseFirestore {
  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_0(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i2.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i7.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_9(this, Invocation.getter(#settings)),
            returnValueForMissingStub: _FakeSettings_9(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i7.Settings);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i7.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i8.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_10<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
            returnValueForMissingStub:
                _FakeCollectionReference_10<Map<String, dynamic>>(
                  this,
                  Invocation.method(#collection, [collectionPath]),
                ),
          )
          as _i8.CollectionReference<Map<String, dynamic>>);

  @override
  _i8.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_11(
              this,
              Invocation.method(#batch, []),
            ),
            returnValueForMissingStub: _FakeWriteBatch_11(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i8.WriteBatch);

  @override
  _i9.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i8.LoadBundleTask loadBundle(_i15.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_12(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
            returnValueForMissingStub: _FakeLoadBundleTask_12(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i8.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i8.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i7.GetOptions? options = const _i7.GetOptions(),
    required _i8.FromFirestore<T>? fromFirestore,
    required _i8.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i9.Future<_i8.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_13<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i8.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_13<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i8.QuerySnapshot<T>>);

  @override
  _i9.Future<_i8.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i7.GetOptions? options = const _i7.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i9.Future<_i8.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_13<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i9.Future<_i8.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_13<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i9.Future<_i8.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i8.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_14<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
            returnValueForMissingStub: _FakeQuery_14<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i8.Query<Map<String, dynamic>>);

  @override
  _i9.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i8.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_15<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
            returnValueForMissingStub:
                _FakeDocumentReference_15<Map<String, dynamic>>(
                  this,
                  Invocation.method(#doc, [documentPath]),
                ),
          )
          as _i8.DocumentReference<Map<String, dynamic>>);

  @override
  _i9.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i9.Stream<void>.empty(),
            returnValueForMissingStub: _i9.Stream<void>.empty(),
          )
          as _i9.Stream<void>);

  @override
  _i9.Future<T> runTransaction<T>(
    _i8.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
            returnValueForMissingStub:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i9.Future<T>);

  @override
  _i9.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i8.PipelineSource pipeline() =>
      (super.noSuchMethod(
            Invocation.method(#pipeline, []),
            returnValue: _FakePipelineSource_17(
              this,
              Invocation.method(#pipeline, []),
            ),
            returnValueForMissingStub: _FakePipelineSource_17(
              this,
              Invocation.method(#pipeline, []),
            ),
          )
          as _i8.PipelineSource);

  @override
  _i9.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
