// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:car_care_app/features/logs/data/models/fuel_log_model.dart';
import 'package:car_care_app/features/logs/data/models/location_model.dart';
import 'package:car_care_app/features/logs/data/models/maintenance_log_model.dart';
import 'package:car_care_app/features/vehicles/data/models/vehicle_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FuelLogModelAdapter());
    registerAdapter(LocationModelAdapter());
    registerAdapter(MaintenanceLogModelAdapter());
    registerAdapter(VehicleModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FuelLogModelAdapter());
    registerAdapter(LocationModelAdapter());
    registerAdapter(MaintenanceLogModelAdapter());
    registerAdapter(VehicleModelAdapter());
  }
}
